package by.azzibom.tetris.view.swing;

import by.azzibom.observer.Observer;
import by.azzibom.tetris.model.State;
import by.azzibom.tetris.model.TetrisEvent;
import by.azzibom.tetris.model.TetrisGame;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;
import java.util.ArrayList;
import java.util.List;

/**
 * окно игры
 *
 * @author Ihar Misevich
 */
public class GameFrame extends JFrame {

    private JPanel nextShapeField;
    private JPanel gameField;

    private JPanel contentField;
    private JLabel removeLineValueLabel;
    private JLabel scoreValueLabel;
    private JLabel speedValueLabel;
    private JLabel statusLabelValue;

    private final TetrisGame game;
    private final DrawSquareStyle drawSquareStyleStrategy;

    public GameFrame(TetrisGame game, DrawSquareStyle drawSquareStyleStrategy) {
        this.game = game;
        this.drawSquareStyleStrategy = drawSquareStyleStrategy;

        $$$setupUI$$$();

        int[] imageSizes = {16, 24, 32, 48, 64, 72, 96, 128, 256};
        List<Image> images = new ArrayList<>(imageSizes.length);
        for (int imageSize : imageSizes) {
            images.add(new ImageIcon(ClassLoader.getSystemResource("images/tetris" + imageSize + ".png")).getImage());
        }
        setIconImages(images);

        super.setTitle(game.getName());
        super.setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);

        super.setContentPane(contentField);

        super.pack();
        super.setResizable(false);

        super.setLocationRelativeTo(null);
//        super.setVisible(true);

        this.game.addObserver(new GameObserver());

        removeLineValueLabel.setText(String.valueOf(game.getRemovedLines()));
        scoreValueLabel.setText(String.valueOf(game.getScore()));
        speedValueLabel.setText(String.valueOf(game.getSpeed()));

    }

    // метод для кастомного создания компонентов
    // компоненты создаются после до конструктора
    private void createUIComponents() {
        this.gameField = new TertisGameField(game, drawSquareStyleStrategy);
        this.nextShapeField = new NextShapeField(game, drawSquareStyleStrategy);

        JMenuBar menuBar = new JMenuBar();

        JMenu menu = menuBar.add(new JMenu("File"));

        JMenuItem menuItem = menu.add("Start");
        menuItem.addActionListener(e -> game.start());
        menu.addSeparator();
        menuItem = menu.add("Exit");
        menuItem.addActionListener(e -> System.exit(0));

        super.setJMenuBar(menuBar);
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        contentField = new JPanel();
        contentField.setLayout(new GridBagLayout());
        contentField.setEnabled(true);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel1.setPreferredSize(new Dimension(202, 402));
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 2.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(10, 10, 10, 5);
        contentField.add(panel1, gbc);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(new Color(-16777216)), null));
        gameField.setMaximumSize(new Dimension(200, 400));
        gameField.setMinimumSize(new Dimension(200, 400));
        gameField.setPreferredSize(new Dimension(200, 400));
        panel1.add(gameField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.fill = GridBagConstraints.BOTH;
        contentField.add(panel2, gbc);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        panel3.setPreferredSize(new Dimension(82, 82));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.insets = new Insets(10, 5, 10, 10);
        panel2.add(panel3, gbc);
        panel3.setBorder(BorderFactory.createTitledBorder(BorderFactory.createLineBorder(Color.black), null));
        nextShapeField.setBackground(new Color(-855310));
        nextShapeField.setMaximumSize(new Dimension(80, 80));
        nextShapeField.setMinimumSize(new Dimension(80, 80));
        nextShapeField.setPreferredSize(new Dimension(80, 80));
        panel3.add(nextShapeField, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new GridBagLayout());
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 2.0;
        gbc.fill = GridBagConstraints.BOTH;
        panel2.add(panel4, gbc);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(panel5, gbc);
        final JLabel label1 = new JLabel();
        label1.setHorizontalAlignment(0);
        label1.setText("remove line:");
        panel5.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        removeLineValueLabel = new JLabel();
        removeLineValueLabel.setHorizontalAlignment(0);
        removeLineValueLabel.setText("0");
        panel5.add(removeLineValueLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(panel6, gbc);
        final JLabel label2 = new JLabel();
        label2.setHorizontalAlignment(0);
        label2.setText("score:");
        panel6.add(label2, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        scoreValueLabel = new JLabel();
        scoreValueLabel.setHorizontalAlignment(0);
        scoreValueLabel.setText("0");
        panel6.add(scoreValueLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        final JPanel panel7 = new JPanel();
        panel7.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.fill = GridBagConstraints.BOTH;
        panel4.add(panel7, gbc);
        final JLabel label3 = new JLabel();
        label3.setHorizontalAlignment(0);
        label3.setText("speed:");
        label3.setVerticalAlignment(0);
        panel7.add(label3, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        speedValueLabel = new JLabel();
        speedValueLabel.setHorizontalAlignment(0);
        speedValueLabel.setText("0");
        panel7.add(speedValueLabel, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        statusLabelValue = new JLabel();
        statusLabelValue.setForeground(new Color(-16777216));
        statusLabelValue.setHorizontalAlignment(0);
        statusLabelValue.setHorizontalTextPosition(11);
        statusLabelValue.setText("pause");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 3;
        gbc.weighty = 0.1;
        gbc.anchor = GridBagConstraints.SOUTH;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        gbc.insets = new Insets(0, 0, 20, 0);
        panel4.add(statusLabelValue, gbc);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentField;
    }

    /**
     * внутренний класс подписчика(наблюдателя)
     *
     * @author Ihar Misevich
     * @version 1.0
     */
    private class GameObserver implements Observer<TetrisEvent<?>> {
//        @Override
//        public void update(Observable o, Object arg) {
//            if (arg != null) {
//                if (arg.equals("removedLines"))
//                    removeLineValueLabel.setText(String.valueOf(game.getRemovedLines()));
//                if (arg.equals("score"))
//                    scoreValueLabel.setText(String.valueOf(game.getScore()));
//                if (arg.equals("speed"))
//                    speedValueLabel.setText(String.valueOf(game.getSpeed()));
//                if (arg.equals("pause") && game.isPause())
//                    statusLabelValue.setEnabled(true);
//                else
//                    statusLabelValue.setEnabled(false);
//
//                if (arg.equals("gameOver") && game.isGameOver()) {
//                    statusLabelValue.setEnabled(true);
//                    statusLabelValue.setForeground(Color.RED);
//                    statusLabelValue.setText("Game Over!");
//                }
//            }
//            repaint();
//        }

        @Override
        public void update(TetrisEvent<?> arg) {
            System.out.println(arg);
            if (arg != null) {
                if (arg.getName().equals("removedLines"))
                    removeLineValueLabel.setText(String.valueOf(game.getRemovedLines()));
                if (arg.getName().equals("score"))
                    scoreValueLabel.setText(String.valueOf(game.getScore()));
                if (arg.getName().equals("speed"))
                    speedValueLabel.setText(String.valueOf(game.getSpeed()));
                if (arg.getName().equals("state")) {
                    if (State.PAUSED.equals(arg.getNewValue())) {
                        System.out.println("pause");
                        statusLabelValue.setEnabled(true);
                    } else if (State.GAME.equals(arg.getNewValue())) {
                        System.out.println("game");
                        statusLabelValue.setEnabled(false);
                    } else if (State.GAME_OVER.equals(arg.getNewValue())) {
                        statusLabelValue.setText("Game Over!");
                        statusLabelValue.setEnabled(true);
                        statusLabelValue.setForeground(Color.RED);
                    }
                }
            }
            repaint();
        }
    }
}
